# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
