# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaSite', '0002_auto_20160813_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('accessToken', models.CharField(max_length=300, null=True)),
                ('accessSecret', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instaSite.User'),
        ),
    ]
