# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaSite', '0003_auto_20160816_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
