# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaSite', '0004_auto_20160817_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('accessToken', models.CharField(max_length=300, null=True)),
                ('accessSecret', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
